name: the-box

services:
  the-box:
    image: wifsimster/the-box:latest
    container_name: the-box
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lan"

      # Entrypoint
      - "traefik.http.routers.the-box.entrypoints=websecure"

      # Router
      - "traefik.http.routers.the-box.rule=Host(`the-box.battistella.ovh`)"
      - "traefik.http.routers.the-box.tls=true"
      - "traefik.http.routers.the-box.tls.certresolver=letsencrypt"

      # Service
      - "traefik.http.services.the-box.loadBalancer.server.port=80"

      # Watchtower automatic update
      - com.centurylinklabs.watchtower.enable=true

    networks:
      lan:

networks:
  lan:
    external: true
