name: the-box

services:
  the-box:
    image: wifsimster/the-box:latest
    container_name: the-box
    restart: unless-stopped
    healthcheck:
      disable: true
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lan"

      # Entrypoint
      - "traefik.http.routers.the-box.entrypoints=websecure"

      # Router
      - "traefik.http.routers.the-box.rule=Host(`the-box.battistella.ovh`)"
      - "traefik.http.routers.the-box.tls=true"
      - "traefik.http.routers.the-box.tls.certresolver=letsencrypt"

      # Service
      - "traefik.http.services.the-box.loadBalancer.server.port=80"

      # Watchtower automatic update
      - com.centurylinklabs.watchtower.enable=true

    networks:
      lan:

  redis:
    image: redis:alpine
    container_name: the-box-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      lan:

  postgres:
    image: postgres:16-alpine
    container_name: the-box-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=thebox
      - POSTGRES_PASSWORD=thebox
      - POSTGRES_DB=thebox
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Europe/Paris
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      lan:

volumes:
  redis-data:
  postgres-data:

networks:
  lan:
    external: true
